### ISSUE TITLE
Пофиксите документацию blessRNG

### ISSUE THREAD

**Issue by nordiauwu** [tamtam-chat/tamtam-bot-api-schema#15]
Мне, вот, сложно понять, это так и надо что у юзера который приходит в message_construction_request'е есть поля
![image](https://user-images.githubusercontent.com/58115165/130326036-af1c9ca8-e7c1-4b56-8e71-c6fcc67cf633.png)
но в других местах и в https://dev.tamtam.chat/#tag/user_model их нет
![image](https://user-images.githubusercontent.com/58115165/130326048-92ffdee2-7b7a-4de2-808b-e38578dec7bc.png)
как мне это понимать? Аватар юзера можно получить только в message_construction_request? Если делаете клон тг то хотябы делайте это качественно, омг.

**Comment by nordiauwu** [comment]
![image](https://user-images.githubusercontent.com/58115165/130326551-662e5b93-4d4a-4cf9-916e-20dca147b687.png)
Так что вам тут надо то? Массив строк или строка с update_type'ами через запятую?

**Comment by achuprin** [comment]
1. В MessageConstructionRequest приходит тип UserWithPhoto. В панели слева перечислены не все используемые типы, а наиболее частые из них. Конкретную модель нужно смотреть в описании метода
2. Arrays of string это описание модели параметров запроса. Comma-separated означает представление этого массива в строке запроса
